name: Terraform CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  terraform:
    name: Validate & Plan - ${{ matrix.example }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        example:
          - examples/cross_account_s3
          - examples/logscale_query

    defaults:
      run:
        working-directory: ${{ matrix.example }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false
        env:
          AWS_DEFAULT_REGION: us-east-1
          TF_VAR_client_id: ${{ secrets.CROWDSTRIKE_CLIENT_ID }}
          TF_VAR_client_secret: ${{ secrets.CROWDSTRIKE_CLIENT_SECRET }}
